### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by BeatLink** [EternityForest/mdNotes#1]

**Comment by EternityForest** [comment]
Not particularly so, I'm not actively developing it at the moment, but I will accept pull requests.

I have a long-term plan to develop a proper  cross platform notetaking solution/wiki  based on distributed database, which will probably be in PyQt and use SQLite files.  But I don't know if I'll actually get around to that.

**Comment by BeatLink** [comment]
Ahh okay :(

**Comment by EternityForest** [comment]
Hey! Just doing a cleanup of my github profile and saw this, so I thought I'd let everyone know that I'm archiving this repo and replacing it with a new, mobile friendly notetaking app called Drayer Journal that also supports Excel-style spreadsheet features and a bunch of other stuff:

https://github.com/EternityForest/hardlinep2p
